export const SET_REPORT_STATUS = "SET_REPORT_STATUS";
export const SET_REPORT_IMAGE = "SET_REPORT_IMAGE";
export const SET_REPORT_LOCATION_SHARED = "SET_REPORT_LOCATION_SHARED";
export const SET_REPORT_LOCATION_FETCHING = "SET_REPORT_LOCATION_FETCHING";
export const SET_REPORT_LOCATION_COORDS = "SET_REPORT_LOCATION_COORDS";
export const SET_REPORT_LOCATION_METHOD = "SET_REPORT_LOCATION_METHOD";
export const SET_REPORT_DETAIL = "SET_REPORT_DETAIL";

export const GET_LOCATION_COORDS = "GET_LOCATION_COORDS";
export const HANDLE_REPORT_IMAGE_UPLOAD = "HANDLE_REPORT_IMAGE_UPLOAD";
